---
- name: Install and set up Postgres 15 in Ubuntu 22.04
  hosts: all
  become: yes
  gather_facts: False


  tasks:
    - name: Hold kubeadm
      ansible.builtin.dpkg_selections:
        name: linux-image-5.15.0-70-generic
        selection: hold
    - name: Update apt repo and cache on all Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600


    - name: Install required packages
      apt:
        update_cache: yes
        name:
          - wget
          - python3-psycopg2
          - acl
          - atop
          - pgtop
          - unzip

        state: latest

    - name: Set up Postgres 15 repo
      shell: |
         echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
         wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      args:
         warn: no
    - name: Install Certificates
      shell: |
         mkdir --parents ~/.postgresql && curl -sfL 'https://storage.yandexcloud.net/cloud-certs/CA.pem' -o ~/.postgresql/root.crt && chmod 0600 ~/.postgresql/root.crt
      become: False

    - name: Install postgresql
      apt:
        name: postgresql-client-15
        update_cache: yes

