---
- name: Install anvanced packets
  hosts: all
  become: yes
  gather_facts: False


  tasks:
    - name: Update apt repo and cache on all Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600


    - name: Install required packages
      apt:
        update_cache: yes
        name:
          - atop
          - pgtop
          - unzip
        state: latest



