apiVersion: v1
kind: Service
metadata:
  name: hello-master
spec:
  ports:
  - port: 5000
    name: plaintext
    targetPort: 5432
  selector:
    connection-pooler: postgres-patroni-pooler
  type: LoadBalancer