apiVersion: v1
kind: Service
metadata:
  name: hello-replica
spec:
  ports:
  - port: 5001
    name: plaintext
    targetPort: 5432
  selector:
    connection-pooler: postgres-patroni-pooler-repl
  type: LoadBalancer
